set si      " smart indent
set sw=4    " shift width
set ts=4    " tab stop (indenting after the beginning of the line)
set mat=0   " don't flash match
set number  " line numbers
set mouse=a " mouse mode

" IDE mode
command IDE source $VIMCONFIG/idemode_unbork.vim

let idemode=$IDEMODE
if idemode == '1'
    IDE
else
    source $VIMCONFIG/autoload/plug.vim
    call plug#begin($VIMCONFIG.'/plugged')
    Plug 'christoomey/vim-tmux-navigator'
    call plug#end()
endif
