
set diffopt+=algorithm:patience
command W w

" IDE mode
command IDE source $VIMCONFIG/idemode.vim

let idemode=$IDEMODE
if idemode == '1'
    IDE
else
	set si      " smart indent
	set sw=4    " shift width
	set ts=4    " tab stop (indenting after the beginning of the line)
	set et		" expand tab
	set mat=0   " don't flash match
	set number  " line numbers
	set mouse=a " mouse mode
	set nosm	" don't show match

    source $VIMCONFIG/autoload/plug.vim
    call plug#begin($VIMCONFIG.'/plugged')
    Plug 'christoomey/vim-tmux-navigator'
    call plug#end()
endif
